n = input('Digite algo: ')
print('A entrada recebida foi:', n)
print('Esta entrada possui {} caracteres.'.format(len(n)))
print('A classe primitiva desta entrada é:', type(n))
print('Somente espaços? ', n.isspace())
print('É Alfa?', n.isalpha())
print('É Numérico?', n.isnumeric())
print('É AlfaNúmerico?', n.isalnum())
print('É Dígito?', n.isdigit())
print('Está em Maiúsculo? ', n.isupper())
print('Está em Minúsculo?', n.islower())
print('Está Capitalizada?', n.istitle())
print('É um Sinal Computacional?', n.isascii())
